<a href="https://colab.research.google.com/github/mublify/Deep_Learning/blob/main/Deep_Learning/Introduction_to_Tensorflow_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Tensorflow in Python

Imagine you have a box of chocolates. This box is a simple container, right? Now, imagine you have a multi-dimensional box, like a Rubik's Cube. This cube has layers, rows, and columns, and each little cube within it can hold a different piece of information.

![Rubik's Cube](https://live.staticflickr.com/3691/11913436786_fa99d2f1bb_b.jpg)

In the world of artificial intelligence, tensors are like these multi-dimensional boxes. They are used to store and process complex data, such as images, videos, and text. For example, an image can be represented as a tensor where each dimension represents the height, width, and color channels of the image.

These tensors are the building blocks of many AI algorithms and models. They allow computers to understand and analyze complex patterns within data, which is crucial for tasks like image recognition, natural language processing, and even self-driving cars.

![Artificial Intelligence](https://img.ccnull.de/1095000/preview/1099986_dc09d38e98721d53ec573553c3e1ff91.jpg)

## Binary Classification

### Getting Bank Notes Data using genfromtxt library

Think of numpy.genfromtxt as a handy tool that helps you tidy up messy data. It's like a magical wand that can transform a messy text file into a clean, organized NumPy array.

In [109]:
import numpy as np
from numpy import genfromtxt
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.0


In [110]:
data=genfromtxt('bank_note_data.txt',delimiter =',')
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

### Dataset Summary

This dataset is a collection of images of genuine and counterfeit banknotes, processed to extract key features. It's commonly used for training and evaluating machine learning models for banknote authentication.

#### Features:

**Variance:** Measures image texture variation.

**Skewness:** Quantifies image asymmetry.

**Curtosis:** Captures image tailedness.

**Entropy:** Reflects image randomness or information content.

#### Labels:
**Class:** Indicates whether the banknote is genuine (1) or counterfeit (0).

In [111]:
labels=data[:,-1]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [112]:
features=data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [113]:
X=features
y=labels

### Train Test Split


To prevent overfitting and ensure the model's ability to generalize to new, unseen data.

In [114]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=0)

### Standardization of Data

To scale data to fit within a specific range, typically [0, 1]. It’s useful when features have varied ranges, and to avoid bias and simplifying compute.

In [115]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

#Identify the number
scaler.fit(X_train)

#Divide the number
X_train_scaled=scaler.transform(X_train)

In [116]:
x_test_scaled=scaler.fit_transform(X_test)

### Building the Neural Network

for learning complex, often a non-linear machine learning model.

In [117]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#### Activation Functions

An activation function takes the input signals from the previous layer and converts them into an output signal that gets sent to the next layer in the network. [Reference](https://thedatainterview.substack.com/p/why-neural-networks-need-an-activation-function)

In [118]:
model=Sequential()

#First hidden layer
model.add(Dense(5, input_dim=4, activation='relu')) #5-neurons, input_dim=4 (number of inputs), activation=function

#Second hidden layer
model.add(Dense(4, activation='relu'))

#Output layer
model.add(Dense(1, activation='sigmoid')) #Sigmoid Activation function is the best option for the output layer of Binary Classification. Not for others.


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### Compile Model

Compile the model by specifying the optimizer, loss function, and evaluation metric. [Reference](https://medium.com/@sumit.kaul.87/building-deep-learning-models-with-keras-a-step-by-step-guide-with-code-examples-68aee4152625)

**Loss Calculation:** The network’s output is compared to the actual answer, and a “loss” (error) is calculated, which reflects how far the prediction is from the target. [Reference](https://medium.com/@njorogeofrey73/a-gental-introduction-to-neural-networks-3ebda1284984)

**Adam Optimizer:** The Adam optimizer combines the advantages of Momentum and RMSProp, enabling adaptive learning-rate adjustments and thereby improving convergence speed.[Reference](https://www.mdpi.com/2223-7747/13/22/3151)

In [119]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

### Train the model

The number of **epochs** is a hyperparameter of gradient descent that controls the number of training samples to work through before the model’s internal parameters are updated. [Reference](https://machinelearningmastery.com/difference-between-a-batch-and-an-epoch)

**Verbose** will bring the model summary at each iteration. [Reference](https://www.analyticsvidhya.com/blog/2021/04/forward-feature-selection-and-its-implementation/)

In [120]:
model.fit(X_train_scaled,y_train, epochs=50, verbose=1)


Epoch 1/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5493 - loss: 0.6914
Epoch 2/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5696 - loss: 0.6855 
Epoch 3/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5416 - loss: 0.6805 
Epoch 4/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5299 - loss: 0.6729
Epoch 5/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5709 - loss: 0.6542 
Epoch 6/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5671 - loss: 0.6452 
Epoch 7/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6128 - loss: 0.6343
Epoch 8/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6857 - loss: 0.6173
Epoch 9/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7424 - loss: 0.5978
Epoch 10/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7572 - loss: 0.5843
Epoch 11/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7905 - loss: 0.5636
Epoch 12/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8189 

### Predicting New Unseen Data

In [121]:
predictions=model.predict(x_test_scaled)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step


In [122]:
print(predictions[:5])

[[0.7838345 ]
 [0.01499303]
 [0.8685787 ]
 [0.11859298]
 [0.01341212]]


The results of a Neural Network is in the form of probabilities of one of the classes (1 or 0)

In [123]:
predicted_classes=np.where(predictions>0.5,1,0)
predicted_classes

array([[1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
    

NumPy’s where() function filters and indexes arrays. It takes a condition as input and returns a boolean array indicating which elements satisfy the condition. The function converts probabilities (in the predictions array) into binary classifications (in the predicted_classes array).

### Evaluating the Model

In [124]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                     │ (None, 5)                   │              25 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_16 (Dense)                     │ (None, 4)                   │              24 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_17 (Dense)                     │ (None, 1)                   │               5 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 164 (660.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 110 (444.00 B)

In [125]:
model.metrics_names

['loss', 'compile_metrics']

In [126]:
from sklearn.metrics import confusion_matrix, classification_report

In [127]:
classification_report(y_test,predicted_classes)

'              precision    recall  f1-score   support\n\n         0.0       0.93      0.96      0.95       157\n         1.0       0.95      0.91      0.93       118\n\n    accuracy                           0.94       275\n   macro avg       0.94      0.93      0.94       275\nweighted avg       0.94      0.94      0.94       275\n'

In [128]:
print(confusion_matrix(y_test,predicted_classes))

[[151   6]
 [ 11 107]]
